using static Managed.LibRaw.Native.LibRaw_internal_thumbnail_formats;

namespace Managed.LibRaw;

public enum InternalThumnailFormat
{
    Unknown = LIBRAW_INTERNAL_THUMBNAIL_UNKNOWN,
    KodakThumb = LIBRAW_INTERNAL_THUMBNAIL_KODAK_THUMB,
    KodakYCbCr = LIBRAW_INTERNAL_THUMBNAIL_KODAK_YCBCR,
    KodakRgb = LIBRAW_INTERNAL_THUMBNAIL_KODAK_RGB,
    Jpeg = LIBRAW_INTERNAL_THUMBNAIL_JPEG,
    Layer = LIBRAW_INTERNAL_THUMBNAIL_LAYER,
    Rollei = LIBRAW_INTERNAL_THUMBNAIL_ROLLEI,
    Ppm = LIBRAW_INTERNAL_THUMBNAIL_PPM,
    Ppm16 = LIBRAW_INTERNAL_THUMBNAIL_PPM16,
    X3f = LIBRAW_INTERNAL_THUMBNAIL_X3F,
    DngYCbCr = LIBRAW_INTERNAL_THUMBNAIL_DNG_YCBCR,
    JpegXl = LIBRAW_INTERNAL_THUMBNAIL_JPEGXL,
}
