using static Managed.LibRaw.Native.LibRaw_progress;

namespace Managed.LibRaw;

[Flags]
public enum ProgressFlags
{
    Start = LIBRAW_PROGRESS_START,
    Open = LIBRAW_PROGRESS_OPEN,
    Identify = LIBRAW_PROGRESS_IDENTIFY,
    SizeAdjust = LIBRAW_PROGRESS_SIZE_ADJUST,
    LoadRaw = LIBRAW_PROGRESS_LOAD_RAW,
    Raw2Image = LIBRAW_PROGRESS_RAW2_IMAGE,
    RemoveZeroes = LIBRAW_PROGRESS_REMOVE_ZEROES,
    BadPixels = LIBRAW_PROGRESS_BAD_PIXELS,
    DarkFrame = LIBRAW_PROGRESS_DARK_FRAME,
    FoveonInterpolate = LIBRAW_PROGRESS_FOVEON_INTERPOLATE,
    ScaleColors = LIBRAW_PROGRESS_SCALE_COLORS,
    PreInterpolate = LIBRAW_PROGRESS_PRE_INTERPOLATE,
    Interpolate = LIBRAW_PROGRESS_INTERPOLATE,
    MixGreen = LIBRAW_PROGRESS_MIX_GREEN,
    MedianFilter = LIBRAW_PROGRESS_MEDIAN_FILTER,
    Highlights = LIBRAW_PROGRESS_HIGHLIGHTS,
    FujiRotate = LIBRAW_PROGRESS_FUJI_ROTATE,
    Flip = LIBRAW_PROGRESS_FLIP,
    ApplyProfile = LIBRAW_PROGRESS_APPLY_PROFILE,
    ConvertRgb = LIBRAW_PROGRESS_CONVERT_RGB,
    Stretch = LIBRAW_PROGRESS_STRETCH,
    Stage20 = LIBRAW_PROGRESS_STAGE20,
    Stage21 = LIBRAW_PROGRESS_STAGE21,
    Stage22 = LIBRAW_PROGRESS_STAGE22,
    Stage23 = LIBRAW_PROGRESS_STAGE23,
    Stage24 = LIBRAW_PROGRESS_STAGE24,
    Stage25 = LIBRAW_PROGRESS_STAGE25,
    Stage26 = LIBRAW_PROGRESS_STAGE26,
    Stage27 = LIBRAW_PROGRESS_STAGE27,
    ThumbLoad = LIBRAW_PROGRESS_THUMB_LOAD,
    Reserved1 = LIBRAW_PROGRESS_TRESERVED1,
    Reserved2 = LIBRAW_PROGRESS_TRESERVED2,
}
